name: Release

on:
  push:
    tags:
      - '*.*'
      - '*.*.*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  label-detector:
    name: Runner Label
    runs-on: label-detector
    outputs:
      runs-on: ${{ steps.detector.outputs.label }}
    steps:
      - name: Detect Label
        id: detector
        run: |
          # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs
          echo "label=$(curl -fsSL https://this-is-nats.appscode.ninja/runs-on/${{ github.repository_owner }}?visibility=${{ github.repository_visibility }})" >> $GITHUB_OUTPUT

  build:
    name: Build
    needs: label-detector
    runs-on: "${{ needs.label-detector.outputs.runs-on }}"
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Print version info
        id: semver
        run: |
          make version

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3
        with:
          cache-image: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Log in to the GitHub Container registry
        env:
          REGISTRY: ghcr.io/kubedb
          DOCKER_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
          USERNAME: 1gtm
        run: |
          docker login ghcr.io --username ${USERNAME} --password ${DOCKER_TOKEN}

      - name: Run checks
        run: |
          make ci

      - name: Build
        run: |
          make release
